export { default as Navbar } from './Navbar/Navbar'
export { default as Footer } from './Footer/Footer'
export { default as Landing } from './Landing/Landing'
export { default as About } from './About/About'
export { default as Achievement } from './Achievement/Achievement'
export { default as AchievementSummary } from './Achievement/AchievementSummary'
export { default as Testimonials } from './Testimonials/Testimonials'
export { default as Education } from './Education/Education'
export { default as Experience } from'./Experience/Experience'
export { default as Contacts } from'./Contacts/Contacts'
export { default as Projects } from'./Projects/Projects'
export { default as Services } from'./Services/Services'
export { default as Gallery } from './Gallery/Gallery'
export { default as VideoGallery } from './VideoGallery/VideoGallery'
export { default as PlayerProfiles } from './PlayerProfiles/PlayerProfiles'
export { default as SingleProject } from './Projects/SingleProject/SingleProject'
export { default as SingleService } from './Services/SingleService/SingleService'
export { default as Admin } from './Admin/Admin'

export { default as BackToTop } from'./BackToTop/BackToTop'